// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhiteLagoon.Infrastructure.Data;

#nullable disable

namespace WhiteLagoon.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250224230448_seedVillaToDb")]
    partial class seedVillaToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhiteLagoon.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(2025, 2, 25, 1, 4, 48, 460, DateTimeKind.Local).AddTicks(6360),
                            Description = "Villa 1 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 1",
                            Occupancy = 6,
                            Price = 1000.0,
                            Sqft = 2000,
                            Updated_Date = new DateTime(2025, 2, 25, 1, 4, 48, 463, DateTimeKind.Local).AddTicks(3711)
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2025, 2, 25, 1, 4, 48, 463, DateTimeKind.Local).AddTicks(4057),
                            Description = "Villa 2 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 2",
                            Occupancy = 8,
                            Price = 2000.0,
                            Sqft = 3000,
                            Updated_Date = new DateTime(2025, 2, 25, 1, 4, 48, 463, DateTimeKind.Local).AddTicks(4066)
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2025, 2, 25, 1, 4, 48, 463, DateTimeKind.Local).AddTicks(4069),
                            Description = "Villa 3 Description",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Villa 3",
                            Occupancy = 10,
                            Price = 3000.0,
                            Sqft = 4000,
                            Updated_Date = new DateTime(2025, 2, 25, 1, 4, 48, 463, DateTimeKind.Local).AddTicks(4071)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
